name: reptrack
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.0
  drift: ^2.31.0
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5
  get: ^4.7.3
  rxdart: ^0.27.7
  intl: ^0.20.2
  audioplayers: ^6.5.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.31.0
  build_runner: ^2.11.1
  rename: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/exercises.csv